### ISSUE TITLE
Mnemonic split - pybtc vs. jsbtc 

### ISSUE THREAD

**Issue by avsync** [bitaps-com/pybtc#18]
I've been trying to get the combine/split mnemonic in pybtc to play nicely and match https://bitaps.com/mnemonic but the implementation must be different. I've tried to understand how the pybtc mnemonic combine/split differs from jsbtc but my understanding of js is pretty much non existent. Any pointers would be appreciated.

**Comment by avsync** [comment]
I managed to figure out some basic javascript, just enough to get a test vectors from jsbtc and now I've found that I can get the output from pybtc to match jsbtc. Neither of them produce a split mnemonic that is recoverable on https://bitaps.com/mnemonic though. What's up with that, what I am doing wrong?

```
let m = 'monkey weird office glove olympic tank vote raven never punch diesel hobby';
console.log("Mnemonic:", m);
let s = btc.splitMnemonic(2, 2, m);
console.log("Split Mnemonic 2/2", s);
console.log("Recovered Mnemonic:", btc.combineMnemonic(s));
```
_Mnemonic: monkey weird office glove olympic tank vote raven never punch diesel hobby

Split Mnemonic 2/2 {"181":"humble owner damage purse verb under sail deputy skin clap exotic problem","254":"room elegant vintage quick culture brown type shallow ignore culture whip spell"}

Recovered Mnemonic: monkey weird office glove olympic tank vote raven never punch diesel hobby_

![restorefs](https://user-images.githubusercontent.com/11985756/91730239-fc1b4c00-eba5-11ea-94f9-ab23f830073e.png)

**Comment by avsync** [comment]
And the same thing in pybtc. I must be missing something...

```
mnemonic = "monkey weird office glove olympic tank vote raven never punch diesel hobby"
print("Mnemonic: ", mnemonic)
split = split_mnemonic(mnemonic, 2, 2)
print("Split Mnemonic: ", split)
combine = combine_mnemonic(split)
print("Recovered Mnemonic: ", combine)
```

_Mnemonic:  monkey weird office glove olympic tank vote raven never punch diesel hobby
Split Mnemonic:  {1: 'curve size try mesh lock pair detail ordinary display flower candy degree', 2: 'tragic obvious divide lyrics rifle fetch grit until surface night series session'}
Recovered Mnemonic:  monkey weird office glove olympic tank vote raven never punch diesel hobby_

![restorefsp](https://user-images.githubusercontent.com/11985756/91732056-fb83b500-eba7-11ea-8608-ab33b940646a.png)

**Comment by 4tochka** [comment]
Please try this branch. https://github.com/bitaps-com/pybtc/tree/new_block_tx

I not yet finished test coverage and no merge in master

Implementation reference https://github.com/bitaps-com/mnemonic-offline-tool/blob/master/BIP/mnemonic-improvement.md

**Comment by 4tochka** [comment]
<img width="1281" alt="Снимок экрана 2020-09-02 в 22 26 56" src="https://user-images.githubusercontent.com/24795003/92021902-83fe8300-ed6b-11ea-9f64-52448dbdabf3.png">
this. branch
 https://github.com/bitaps-com/pybtc/tree/new_block_tx
 implemented  according BIP

**Comment by 4tochka** [comment]
tests https://github.com/bitaps-com/pybtc/blob/new_block_tx/tests/test_bip39_mnemonic_functions.py#L111

**Comment by avsync** [comment]
Thank you for looking into this, much appreciated! I can confirm combine is working as expected in this branch.

**Comment by 4tochka** [comment]
Hope to finish work on latest version of pybtc soon!

**Comment by 4tochka** [comment]
merged to master
