### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by kayak-dodd** [bitaps-com/pybtc#21]
Not really sure if this is the right place to post this, but I hope so, as I'd really like to try out this library for my project.

OS: Ubuntu 20
python version: 3.9

I created a relatively fresh conda environment and made sure pip was installed and logged the result to a file as it won't install.

> 2021-01-28T16:08:55,623 Using pip 20.3.3 from /home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip (python 3.9)
> 2021-01-28T16:08:55,625 Non-user install because site-packages writeable
> 2021-01-28T16:08:55,749 Created temporary directory: /tmp/pip-ephem-wheel-cache-1aid68qt
> 2021-01-28T16:08:55,749 Created temporary directory: /tmp/pip-req-tracker-clr4redk
> 2021-01-28T16:08:55,749 Initialized build tracking at /tmp/pip-req-tracker-clr4redk
> 2021-01-28T16:08:55,749 Created build tracker: /tmp/pip-req-tracker-clr4redk
> 2021-01-28T16:08:55,749 Entered build tracker: /tmp/pip-req-tracker-clr4redk
> 2021-01-28T16:08:55,749 Created temporary directory: /tmp/pip-install-dd8hl917
> 2021-01-28T16:08:55,756 1 location(s) to search for versions of pybtc:
> 2021-01-28T16:08:55,756 * https://pypi.org/simple/pybtc/
> 2021-01-28T16:08:55,756 Fetching project page and analyzing links: https://pypi.org/simple/pybtc/
> 2021-01-28T16:08:55,756 Getting page https://pypi.org/simple/pybtc/
> 2021-01-28T16:08:55,757 Found index url https://pypi.org/simple
> 2021-01-28T16:08:55,983   Found link https://files.pythonhosted.org/packages/65/e2/fb2d7995aa3d1b004e6def6f5f46ce45ffbb731b5d6315bc64ec7dc81492/pybtc-2.0.3-py2.py3-none-any.whl#sha256=5ad2db71b91244dbf9a7de7116f66bed33da9e38b2a658a83ae8e33658852535 (from https://pypi.org/simple/pybtc/), version: 2.0.3
> 2021-01-28T16:08:55,983   Found link https://files.pythonhosted.org/packages/06/de/5e4eebd241d1094ac0b3ef17f16eaabca072142ca75f51f190d7f9ffef0f/pybtc-2.0.3.tar.gz#sha256=7d0dc199cb01ff3056755b6f0a2a6d5696b3185fd09d817fdadc3c8db601a679 (from https://pypi.org/simple/pybtc/), version: 2.0.3
> 2021-01-28T16:08:55,983   Found link https://files.pythonhosted.org/packages/48/ce/c30dbb7423d567a4cb26f926fa5b4d17bd91fc63a8ea45c7ca312826c13f/pybtc-2.0.4-py2.py3-none-any.whl#sha256=b28395befade522c9b54c52595cd791cfec8571c3adc94df4b661f85291ec148 (from https://pypi.org/simple/pybtc/), version: 2.0.4
> 2021-01-28T16:08:55,983   Found link https://files.pythonhosted.org/packages/3e/09/ef6d7d2f5d9e37d656aa52531830d6e0434f5f0d8e196c6876f733f8d2ed/pybtc-2.0.6-py2.py3-none-any.whl#sha256=e203d4e8ef5c3fae4d255db3a76d549f83db16356406a625617f84e64089d5fb (from https://pypi.org/simple/pybtc/), version: 2.0.6
> 2021-01-28T16:08:55,983   Found link https://files.pythonhosted.org/packages/e8/dc/28773eee32d5252d74acb05089dd4a6c7f38ebe68e6e36970938148d94d0/pybtc-2.0.7-py2.py3-none-any.whl#sha256=879362a5a47c4de50c3a1fc1d6d3151fb24728c3c12de8c57a60727359999b5f (from https://pypi.org/simple/pybtc/), version: 2.0.7
> 2021-01-28T16:08:55,983   Found link https://files.pythonhosted.org/packages/1a/8c/51fa7a102c1fa36874bcabda7e6de592bf26997b7c5c1b6f40940a908eaa/pybtc-2.0.8-py2.py3-none-any.whl#sha256=5ba0b4c818d3ee1336f68bb6a8faa8ddc8eb354b550c55b3e51a8594cb24ba54 (from https://pypi.org/simple/pybtc/), version: 2.0.8
> 2021-01-28T16:08:55,984   Found link https://files.pythonhosted.org/packages/a1/66/1f3c4ae65452d8e84f1524b797dcee919794f449ce912c730dd1e45e0008/pybtc-2.0.9-py3-none-any.whl#sha256=0060b53eb81c9a9402e210cdca4f5ac456f0e76138764b897ecb5344c8589af7 (from https://pypi.org/simple/pybtc/), version: 2.0.9
> 2021-01-28T16:08:55,984 Given no hashes to check 7 links for project 'pybtc': discarding no candidates
> 2021-01-28T16:08:55,995 Collecting pybtc
> 2021-01-28T16:08:55,996   Created temporary directory: /tmp/pip-unpack-odppp7t4
> 2021-01-28T16:08:55,1000   Using cached pybtc-2.0.9-py3-none-any.whl (1.4 MB)
> 2021-01-28T16:08:56,006   Added pybtc from https://files.pythonhosted.org/packages/a1/66/1f3c4ae65452d8e84f1524b797dcee919794f449ce912c730dd1e45e0008/pybtc-2.0.9-py3-none-any.whl#sha256=0060b53eb81c9a9402e210cdca4f5ac456f0e76138764b897ecb5344c8589af7 to build tracker '/tmp/pip-req-tracker-clr4redk'
> 2021-01-28T16:08:56,007   Removed pybtc from https://files.pythonhosted.org/packages/a1/66/1f3c4ae65452d8e84f1524b797dcee919794f449ce912c730dd1e45e0008/pybtc-2.0.9-py3-none-any.whl#sha256=0060b53eb81c9a9402e210cdca4f5ac456f0e76138764b897ecb5344c8589af7 from build tracker '/tmp/pip-req-tracker-clr4redk'
> 2021-01-28T16:08:56,009 1 location(s) to search for versions of secp256k1:
> 2021-01-28T16:08:56,009 * https://pypi.org/simple/secp256k1/
> 2021-01-28T16:08:56,009 Fetching project page and analyzing links: https://pypi.org/simple/secp256k1/
> 2021-01-28T16:08:56,009 Getting page https://pypi.org/simple/secp256k1/
> 2021-01-28T16:08:56,009 Found index url https://pypi.org/simple
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/c3/13/4ade54b0d26b47fa39b5aec418b308e4fdfeeb02e48ca948d9cc88ece18c/secp256k1-0.1.1.tar.gz#sha256=3cc1b5795d9d37c6f93c18917517a73fc77ccfc39432cc557305a385da836145 (from https://pypi.org/simple/secp256k1/), version: 0.1.1
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/54/1c/b481eb788b4a9be0b38bfe34b9faadc2ab81b6a6cd7fa7c8b28237afd407/secp256k1-0.1.2.tar.gz#sha256=6512e7cbf97a979aeab2218d53de38ce54bfc5a8b3266cc6a4741cddb075e359 (from https://pypi.org/simple/secp256k1/), version: 0.1.2
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/67/20/773fe4c4c1f8696a1798c754bdee07402725e172a6c6e235bfde7454c07f/secp256k1-0.1.5.tar.gz#sha256=693e51da7c6cf94357156b07b3f71cc3a9fc2cb8adef4e3a380af9db3429dace (from https://pypi.org/simple/secp256k1/), version: 0.1.5
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/5c/78/fbc5489e1b6e1eda40458cfbadc32e50c9e1784ce6596ca738458b5b9432/secp256k1-0.2.0.tar.gz#sha256=9a887749a851cf1349aa22dbae8bb2b98d023183c75cd3e540c9f7c5a122146b (from https://pypi.org/simple/secp256k1/), version: 0.2.0
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/fe/d3/dd4e52b0b8b44a83d2bdddb5b67245d3802f7f4bee8a4a476c8951aaef3b/secp256k1-0.3.0.tar.gz#sha256=c2fd719386676098a42c91bfa5c661b710c0ab2d57ec594fbc68f1ef9dd5a74c (from https://pypi.org/simple/secp256k1/), version: 0.3.0
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/2b/0f/10fa4f8a79cd643c5fbb9778a92a64ec2caa6812610504dcf4e761337591/secp256k1-0.3.1.tar.gz#sha256=9ef9c06ca951cab4cfd5bf6a88bfae2be7bde965fceb12718f325c149e0598c7 (from https://pypi.org/simple/secp256k1/), version: 0.3.1
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/36/4f/94c68aa33d4e70267880d114b9315676a38c276f4ed165ac956f54cf5fd5/secp256k1-0.5.1.tar.gz#sha256=5658112a4f254027639b6497a11157e5dd81b920e5aa1bbd6632bd36a537f44e (from https://pypi.org/simple/secp256k1/), version: 0.5.1
> 2021-01-28T16:08:56,051   Found link https://files.pythonhosted.org/packages/8f/e3/d518af6cb7a6254fb2df19be0692f02427433827d6b77ba5e9569971256d/secp256k1-0.7.0.tar.gz#sha256=b6f3b2e150c30d52721d2509c9196fdbce23f7416541998be5c95bfba155b464 (from https://pypi.org/simple/secp256k1/), version: 0.7.0
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/ba/38/f40c73e3dc470f6c271f04b244d2234ba77c6e3498f4dbb9b42c2239032e/secp256k1-0.7.2.tar.gz#sha256=0638fd96e46d73f112b33e7748810377a1fc1d05665bf2634d811c2ecb2e6229 (from https://pypi.org/simple/secp256k1/), version: 0.7.2
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/a3/ca/3cba4a6ae45d4337c1758dd68a76f0e858c4b09057a019ce71e995d34351/secp256k1-0.8.1.tar.gz#sha256=3972e5ba3ff54f04bf2bdafdbc305369eea5a6423c4cb79ce27a8650d2d842a2 (from https://pypi.org/simple/secp256k1/), version: 0.8.1
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/89/a5/23e9fcb0921c120a06cf9992237936a382afa6f6e79f9336ae9a34de9cc0/secp256k1-0.8.2.tar.gz#sha256=ad0a188fd5862c8c6d2b54dd0a7398a11ad6db112cfb65b4c1339084671271d1 (from https://pypi.org/simple/secp256k1/), version: 0.8.2
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/bb/52/f0c86f5172befde11ce3c0de2c7ea8c53d4188b8dca9294a98d94bae757d/secp256k1-0.8.5.tar.gz#sha256=9c5839a2fd550fa0813b1bb972bdf0776996e8dffb5458a4920a1e37597b3a53 (from https://pypi.org/simple/secp256k1/), version: 0.8.5
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/d8/e7/49c18867b1886db481003c6a9984871898bbcdc9dcc96fd11ce94f77c34f/secp256k1-0.9.0.tar.gz#sha256=d53b6d27bea5d48f60b7bdf06a634424a41813901c334958c46107c381923e3e (from https://pypi.org/simple/secp256k1/), version: 0.9.0
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/b9/51/e6f8231b92b6eeaf0e73697089232af31098ed4ae651e33948f63365c2e1/secp256k1-0.10.0.tar.gz#sha256=16399332f095b2336f5de7e378c4213fff61e40b570ae563914307e01d232283 (from https://pypi.org/simple/secp256k1/), version: 0.10.0
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/ac/43/b7412740835674c406be622eb6e1703bc0a7bcf782aec022c8091c93e3fb/secp256k1-0.11.0.tar.gz#sha256=25492b6c9cdf0df5818a047a09f4a34abe1d04cc559efc1a6d87e529c9519c91 (from https://pypi.org/simple/secp256k1/), version: 0.11.0
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/3a/11/e7540a3c43a8df39b8cdd32d96f14a44cc000164c75db332a61b260a4cf0/secp256k1-0.11.1.tar.gz#sha256=6270fd40acc271d4753f37ffe83d64562e4b39f1a4cd8fa6617ee03ec3d24bc5 (from https://pypi.org/simple/secp256k1/), version: 0.11.1
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/53/e7/2c4a926c1caef58432bf6bc8bee4c15f81f243492b07d97e5db10c259600/secp256k1-0.12.0.tar.gz#sha256=868a477254913e25cf75eced5cd42799aca4c1d9aac73560727d24dc4cdc810a (from https://pypi.org/simple/secp256k1/), version: 0.12.0
> 2021-01-28T16:08:56,052   Found link https://files.pythonhosted.org/packages/ac/b6/04913a10c7f38ee665f5c439129cb1ae918b183c528c8d67cc5b4b0ba10e/secp256k1-0.12.1.tar.gz#sha256=b4733e23fd1b4ac3ec9088e7d98c5e8fe52891565923cfa4f88b54dcffee327f (from https://pypi.org/simple/secp256k1/), version: 0.12.1
> 2021-01-28T16:08:56,053   Found link https://files.pythonhosted.org/packages/d3/25/6e12ba68b576760e859dc8e42a94745b2e71935808e76712c4917e6e8f04/secp256k1-0.13.0.tar.gz#sha256=765e3a3ac4b6da77ffff4d7b4ff281099eb1165b6c1f91fd2033e11228ac146e (from https://pypi.org/simple/secp256k1/), version: 0.13.0
> 2021-01-28T16:08:56,053   Found link https://files.pythonhosted.org/packages/e1/52/0f09db087830257dc5f9bb3d322ab8c02ee17e6c15cc3e2f02f8610a3eb2/secp256k1-0.13.1.tar.gz#sha256=dfb27966dd2b83cada2d87f539bb36d13e2c6b064120e6c96e4f9de497f42dec (from https://pypi.org/simple/secp256k1/), version: 0.13.1
> 2021-01-28T16:08:56,053   Skipping link: none of the wheel's tags match: cp27-cp27m-macosx_10_6_intel: https://files.pythonhosted.org/packages/1d/3b/b17ca1c9d4460e91e4d243c3f06cfbd14435879744134371a3ef00e879e5/secp256k1-0.13.2-cp27-cp27m-macosx_10_6_intel.whl#sha256=a755c85947b70c69cf318412bfd12889863e70ddf76b588701835a4da5322d55 (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,053   Skipping link: none of the wheel's tags match: cp27-cp27m-manylinux1_x86_64: https://files.pythonhosted.org/packages/c8/22/95038ee6e1362f8177a1ad7af0912ae2de290710a8b292c04edc8e125420/secp256k1-0.13.2-cp27-cp27m-manylinux1_x86_64.whl#sha256=a598f2223ed3bf55bb7e317c5ebd1a316b3b4d65db26de32554bb84adf026eae (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,053   Skipping link: none of the wheel's tags match: cp27-cp27mu-manylinux1_x86_64: https://files.pythonhosted.org/packages/ae/6c/252432b113ef1a8eaaa640cdbc5ba1b5cd5de1843ab5e95c5d457b8bef20/secp256k1-0.13.2-cp27-cp27mu-manylinux1_x86_64.whl#sha256=2ad20bb8553425be795ecaf6641a510470701fa6a7aa9c54395d3989c070ab4c (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,053   Skipping link: none of the wheel's tags match: cp33-cp33m-manylinux1_x86_64: https://files.pythonhosted.org/packages/26/41/46db62fc420185ad5e1630eb619cdf3b2271047d2687c67e68c4757eae0d/secp256k1-0.13.2-cp33-cp33m-manylinux1_x86_64.whl#sha256=e9842fdc3b24c3174f49794d93b10b2013aa7b5d7029d12989458482c95ee56a (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,053   Skipping link: none of the wheel's tags match: cp34-cp34m-macosx_10_6_intel: https://files.pythonhosted.org/packages/6f/30/f60541c3d0e5d37dfaac39932c61202dd752759ba8ed1935f5bfba0f1880/secp256k1-0.13.2-cp34-cp34m-macosx_10_6_intel.whl#sha256=5cded8e5d241dd92f6e55fd7462ff74e4edcbe97850b7bf4378cc56e48e446d7 (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,054   Skipping link: none of the wheel's tags match: cp34-cp34m-manylinux1_x86_64: https://files.pythonhosted.org/packages/d6/2e/a2fd1e75e35d2ecc8ba9a662bc65407c12cc9a0f2e9c68d19c4be0e7bf98/secp256k1-0.13.2-cp34-cp34m-manylinux1_x86_64.whl#sha256=e86eab58d0c2e93c08483c8a8546fe54ade8150ff4a1f320417d647635cb133b (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,054   Skipping link: none of the wheel's tags match: cp35-cp35m-macosx_10_6_intel: https://files.pythonhosted.org/packages/70/3f/a14ce44749cef2c1a9a7ca3356f8c6fde7b3570f21d19403055cd32923cf/secp256k1-0.13.2-cp35-cp35m-macosx_10_6_intel.whl#sha256=29521dda0f3ad51afc26141d9a564b40bb39e84d27046164c502774b22ea2f9c (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,054   Skipping link: none of the wheel's tags match: cp35-cp35m-manylinux1_x86_64: https://files.pythonhosted.org/packages/d8/8d/997e0534cfa2fbfcba5cf32fab00aaeae4a48f965d4f8961a303e01dd315/secp256k1-0.13.2-cp35-cp35m-manylinux1_x86_64.whl#sha256=df29091e6ac74bb0683a44d57411bd59c6c99d04d79ef4e396e4a67d91f6bd65 (from https://pypi.org/simple/secp256k1/)
> 2021-01-28T16:08:56,054   Found link https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz#sha256=a3b43e02d321c09eafa769a6fc2c156f555cab3a7db62175ef2fd21e16cdf20c (from https://pypi.org/simple/secp256k1/), version: 0.13.2
> 2021-01-28T16:08:56,054 Given no hashes to check 21 links for project 'secp256k1': discarding no candidates
> 2021-01-28T16:08:56,060 Collecting secp256k1
> 2021-01-28T16:08:56,061   Created temporary directory: /tmp/pip-unpack-2ybfbz4t
> 2021-01-28T16:08:56,063   Using cached secp256k1-0.13.2.tar.gz (156 kB)
> 2021-01-28T16:08:56,090   Added secp256k1 from https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz#sha256=a3b43e02d321c09eafa769a6fc2c156f555cab3a7db62175ef2fd21e16cdf20c (from pybtc) to build tracker '/tmp/pip-req-tracker-clr4redk'
> 2021-01-28T16:08:56,090     Running setup.py (path:/tmp/pip-install-dd8hl917/secp256k1_13f31e874da44e2f84d6dc04152bd060/setup.py) egg_info for package secp256k1
> 2021-01-28T16:08:56,090     Created temporary directory: /tmp/pip-pip-egg-info-5hjza7cm
> 2021-01-28T16:08:56,090     Running command python setup.py egg_info
> 2021-01-28T16:08:56,321     Traceback (most recent call last):
> 2021-01-28T16:08:56,322       File "<string>", line 1, in <module>
> 2021-01-28T16:08:56,322       File "/tmp/pip-install-dd8hl917/secp256k1_13f31e874da44e2f84d6dc04152bd060/setup.py", line 41, in <module>
> 2021-01-28T16:08:56,322         if [int(i) for i in setuptools_version.split('.')] < [3, 3]:
> 2021-01-28T16:08:56,322       File "/tmp/pip-install-dd8hl917/secp256k1_13f31e874da44e2f84d6dc04152bd060/setup.py", line 41, in <listcomp>
> 2021-01-28T16:08:56,322         if [int(i) for i in setuptools_version.split('.')] < [3, 3]:
> 2021-01-28T16:08:56,322     ValueError: invalid literal for int() with base 10: 'post20210125'
> 2021-01-28T16:08:56,342 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 2021-01-28T16:08:56,342 Exception information:
> 2021-01-28T16:08:56,342 Traceback (most recent call last):
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
> 2021-01-28T16:08:56,342     status = self.run(options, args)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
> 2021-01-28T16:08:56,342     return func(self, options, args)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
> 2021-01-28T16:08:56,342     requirement_set = resolver.resolve(
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
> 2021-01-28T16:08:56,342     self._result = resolver.resolve(
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
> 2021-01-28T16:08:56,342     state = resolution.resolve(requirements, max_rounds=max_rounds)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
> 2021-01-28T16:08:56,342     failure_causes = self._attempt_to_pin_criterion(name, criterion)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
> 2021-01-28T16:08:56,342     criteria = self._get_criteria_to_update(candidate)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
> 2021-01-28T16:08:56,342     for r in self._p.get_dependencies(candidate):
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
> 2021-01-28T16:08:56,342     return [
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
> 2021-01-28T16:08:56,342     return [
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 257, in iter_dependencies
> 2021-01-28T16:08:56,342     requires = self.dist.requires() if with_requires else ()
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
> 2021-01-28T16:08:56,342     self._prepare()
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
> 2021-01-28T16:08:56,342     dist = self._prepare_distribution()
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
> 2021-01-28T16:08:56,342     return self._factory.preparer.prepare_linked_requirement(
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
> 2021-01-28T16:08:56,342     return self._prepare_linked_requirement(req, parallel_builds)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
> 2021-01-28T16:08:56,342     dist = _get_prepared_distribution(
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
> 2021-01-28T16:08:56,342     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
> 2021-01-28T16:08:56,342     self.req.prepare_metadata()
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
> 2021-01-28T16:08:56,342     self.metadata_directory = self._generate_metadata()
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
> 2021-01-28T16:08:56,342     return generate_metadata_legacy(
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
> 2021-01-28T16:08:56,342     call_subprocess(
> 2021-01-28T16:08:56,342   File "/home/mark/miniconda3/envs/bitcoin/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
> 2021-01-28T16:08:56,342     raise InstallationError(exc_msg)
> 2021-01-28T16:08:56,342 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 2021-01-28T16:08:56,374 Removed secp256k1 from https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz#sha256=a3b43e02d321c09eafa769a6fc2c156f555cab3a7db62175ef2fd21e16cdf20c (from pybtc) from build tracker '/tmp/pip-req-tracker-clr4redk'
> 2021-01-28T16:08:56,374 Removed build tracker: '/tmp/pip-req-tracker-clr4redk'

I have tried:
`sudo apt install libsecp256k1-dev`

and:
`sudo apt-get install libssl-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev libyaml-cpp-dev`

Also tried installing by cloning the repo. Nothing is working and I'm not sure what else to try.

edit: I've spent way too much time on this and I think the issue is with secp256k1 as I am unable to install that either but I have no idea why

**Comment by 4tochka** [comment]
FROM ubuntu:20.04
MAINTAINER Aleksey Karpov <admin@bitaps.com>
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf
ENV TZ="America/New_York"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev
RUN apt-get -y install git
RUN pip3 install git+https://github.com/bitaps-com/pybtc@new_block_tx

Just tested docker with ubuntu 20

use  pip3 install git+https://github.com/bitaps-com/pybtc@new_block_tx
