### ISSUE TITLE
Ability to set constants in pybtc.constants to support alt coins

### ISSUE THREAD

**Issue by Lvl4Sword** [bitaps-com/pybtc#26]
**Describe the bug**

Ability to easily set a lot of constants from pybtc.constants rather than having to go in and hardcode anything by editing pybtc/constants.py

**To Reproduce**

Self-explanatory from above

**Additional context**

No additional context needed

**Comment by 4tochka** [comment]
Why did you classify it as a bug?

**Comment by Lvl4Sword** [comment]
> Why did you classify it as a bug?

That's a good question, honestly. I don't think I saw the blank issue section initially.
Either way, #27 starts on this. Is there anything else needed to accept that PR?

**Comment by Lvl4Sword** [comment]
Circling back to this.
Is there anything that needs done for this?
