### ISSUE TITLE
sign_message keeps giving same signature,, for the same private key and message

### ISSUE THREAD

**Issue by legion2002** [bitaps-com/pybtc#31]
**Describe the bug**
When I try signing the same message with the same private key multiple times, the function keeps returning the same signature.
But according to standard EDSA algorithms, the signatures would be different every time. Am I doing something wrong?

**To Reproduce**
import pybtc

pk = "Kz36wrYMg9cnKmpV6aucemPa1EAoxwKRo5DBsBML7dLbXbgcsE6K"

public = pybtc.private_to_public_key(pk)
print("public = " + public)

a = pybtc.sign_message("6865790D0A", pk, hex=True)
print(a)
b = pybtc.verify_signature(a, public, "6865790D0A")
print(b)

**Additional context**
https://stackoverflow.com/questions/56520582/digital-signature-different-everytime/56527077#:~:text=The%20same%20data%20will%20give%20the%20same%20signature%20every%20time.

**Comment by 4tochka** [comment]
Please read this document 
https://datatracker.ietf.org/doc/html/rfc6979

Bitcoin use rfc6979
